version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "7000:7000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/ts_api
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ts_api